#!/usr/bin/env python
import rospy

def main():
    rospy.init_node('asker_learning_agent')
    rate = rospy.Rate(10)

    while not rospy.is_shutdown():
        rospy.loginfo('Hello!')
        rate.sleep()

if __name__ == '__main__':
    try:
        main()
    except rospy.ROSInterruptException:
        pass